/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GActionCard: typeof import('./../components/cards/GActionCard.vue')['default']
    GBadge: typeof import('./../components/base/GBadge.vue')['default']
    GButton: typeof import('./../components/base/GButton.vue')['default']
    GCard: typeof import('./../components/base/GCard.vue')['default']
    GCircleProgress: typeof import('./../components/feedback/GCircleProgress.vue')['default']
    GEmptyState: typeof import('./../components/feedback/GEmptyState.vue')['default']
    GErrorState: typeof import('./../components/feedback/GErrorState.vue')['default']
    GFormField: typeof import('./../components/form/GFormField.vue')['default']
    GHostInput: typeof import('./../components/form/GHostInput.vue')['default']
    GIcon: typeof import('./../components/icons/GIcon.vue')['default']
    GIconButton: typeof import('./../components/base/GIconButton.vue')['default']
    GInput: typeof import('./../components/form/GInput.vue')['default']
    GLabel: typeof import('./../components/form/GLabel.vue')['default']
    GNumberInput: typeof import('./../components/form/GNumberInput.vue')['default']
    GPageContainer: typeof import('./../components/layout/GPageContainer.vue')['default']
    GPageHeader: typeof import('./../components/layout/GPageHeader.vue')['default']
    GPasswordInput: typeof import('./../components/form/GPasswordInput.vue')['default']
    GPortInput: typeof import('./../components/form/GPortInput.vue')['default']
    GProgress: typeof import('./../components/feedback/GProgress.vue')['default']
    GSearchInput: typeof import('./../components/form/GSearchInput.vue')['default']
    GSectionHeader: typeof import('./../components/layout/GSectionHeader.vue')['default']
    GSkeleton: typeof import('./../components/feedback/GSkeleton.vue')['default']
    GSpinner: typeof import('./../components/feedback/GSpinner.vue')['default']
    GStatCard: typeof import('./../components/cards/GStatCard.vue')['default']
    GStatusBadge: typeof import('./../components/status/GStatusBadge.vue')['default']
    GStatusDot: typeof import('./../components/status/GStatusDot.vue')['default']
    GTextarea: typeof import('./../components/form/GTextarea.vue')['default']
    GTokenInput: typeof import('./../components/form/GTokenInput.vue')['default']
    LangSwitch: typeof import('./../components/common/LangSwitch.vue')['default']
    NavItem: typeof import('./../components/common/NavItem.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    ProjectCard: typeof import('./../components/business/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerCard: typeof import('./../components/business/ServerCard.vue')['default']
    StatisticsCard: typeof import('./../components/business/StatisticsCard.vue')['default']
    TunnelCard: typeof import('./../components/business/TunnelCard.vue')['default']
  }
}
