title: "idea: "
labels: ["idea"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      placeholder: What should Gate consider?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or opportunity
  - type: textarea
    id: tradeoffs
    attributes:
      label: Tradeoffs
category: Ideas
