blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/Somirk134/Gate/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://github.com/Somirk134/Gate/security/policy
    about: Please report security vulnerabilities here.
